drop schema if exists spring cascade;
create schema spring;
set search_path to spring;

create table users_ (
                        id  integer generated by default as identity primary key,
                        login    varchar(255),
                        name     varchar(255),
                        password varchar(255),
                        role     varchar(255)
);

create table groups_ (
    id  integer generated by default as identity primary key,
    deleted boolean not null default false,
    name    varchar(255)
);

create table sub_groups (
    id  integer generated by default as identity primary key,
    deleted  boolean not null default false,
    name     varchar(255),
    group_id integer references groups_
);

create table goods (
    id  bigint generated by default as identity primary key,
    deleted boolean not null default false,
    name varchar(255),
    sub_group_id integer references sub_groups
);

create table spring_log (
    id bigint generated by default as identity primary key,
    user_id integer not null,
    entity bigint not null,
    info varchar(255),
    table_id smallint
);